bumps:
  - file: backend/pyproject.toml
    regex:
      - pattern: 'version\s*=\s*".*"'
        semver: true
  - file: frontend/package.json
    json:
      - path: "version"
        semver: true

changelog:
  include:
    - feat
    - fix
    - perf
    - refactor
  exclude:
    - "^Merge"
    - "^chore"
  trimHeader: true

hooks:
  afterBump:
    - cd frontend && npm install --package-lock-only

git:
  includeArtifacts:
    - frontend/package-lock.json

commitAuthor:
  name: uplift-bot
  email: uplift-bot@users.noreply.github.com

annotatedTags: true
