bumps:
  - file: backend/pyproject.toml
    regex:
      - pattern: 'version\s*=\s*".*"'
        semver: true
  - file: frontend/package.json
    json:
      - path: "version"
        semver: true

changelog:
  include:
    - feat
    - fix
    - perf
    - refactor
  exclude:
    - "^Merge"
    - "^chore"
  trimHeader: true

hooks:
  afterBump:
    - echo "Syncing lockfile version..." && cd frontend && npm install --package-lock-only && cd .. && git add frontend/package-lock.json && echo "Staged lockfile"

git:
  # Whitelist only — prevents Uplift's dirty-check from failing if lockfile
  # is already modified. The actual staging is done by the afterBump hook above.
  includeArtifacts:
    - frontend/package-lock.json

commitAuthor:
  name: uplift-bot
  email: uplift-bot@users.noreply.github.com

annotatedTags: true
