"""Increase percentage column precision

Revision ID: 7ab2385590c1
Revises: c929391b3002
Create Date: 2025-11-29 11:30:27.295006

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '7ab2385590c1'
down_revision: Union[str, None] = 'c929391b3002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'discount_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.alter_column('books', 'roi_pct',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=7, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('books', 'roi_pct',
               existing_type=sa.Numeric(precision=7, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.alter_column('books', 'discount_pct',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###
