"""Initial schema

Revision ID: c929391b3002
Revises:
Create Date: 2025-11-29 11:28:50.130754

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'c929391b3002'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('authors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('birth_year', sa.Integer(), nullable=True),
    sa.Column('death_year', sa.Integer(), nullable=True),
    sa.Column('era', sa.String(length=50), nullable=True),
    sa.Column('first_acquired_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('binders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=True),
    sa.Column('authentication_markers', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('publishers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('tier', sa.String(length=10), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cognito_sub', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('display_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cognito_sub')
    )
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=True),
    sa.Column('publisher_id', sa.Integer(), nullable=True),
    sa.Column('binder_id', sa.Integer(), nullable=True),
    sa.Column('publication_date', sa.String(length=50), nullable=True),
    sa.Column('year_start', sa.Integer(), nullable=True),
    sa.Column('year_end', sa.Integer(), nullable=True),
    sa.Column('edition', sa.String(length=100), nullable=True),
    sa.Column('volumes', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('inventory_type', sa.String(length=20), nullable=False),
    sa.Column('binding_type', sa.String(length=50), nullable=True),
    sa.Column('binding_authenticated', sa.Boolean(), nullable=False),
    sa.Column('binding_description', sa.Text(), nullable=True),
    sa.Column('condition_grade', sa.String(length=20), nullable=True),
    sa.Column('condition_notes', sa.Text(), nullable=True),
    sa.Column('value_low', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('value_mid', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('value_high', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('purchase_date', sa.Date(), nullable=True),
    sa.Column('purchase_source', sa.String(length=200), nullable=True),
    sa.Column('discount_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('roi_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('provenance', sa.Text(), nullable=True),
    sa.Column('legacy_row', sa.Integer(), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['authors.id'], ),
    sa.ForeignKeyConstraint(['binder_id'], ['binders.id'], ),
    sa.ForeignKeyConstraint(['publisher_id'], ['publishers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('books_category_idx', 'books', ['category'], unique=False)
    op.create_index('books_inventory_type_idx', 'books', ['inventory_type'], unique=False)
    op.create_index('books_search_idx', 'books', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index('books_status_idx', 'books', ['status'], unique=False)
    op.create_table('book_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('executive_summary', sa.Text(), nullable=True),
    sa.Column('condition_assessment', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('binding_elaborateness_tier', sa.Integer(), nullable=True),
    sa.Column('market_analysis', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('historical_significance', sa.Text(), nullable=True),
    sa.Column('recommendations', sa.Text(), nullable=True),
    sa.Column('risk_factors', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('full_markdown', sa.Text(), nullable=True),
    sa.Column('source_filename', sa.String(length=500), nullable=True),
    sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id')
    )
    op.create_index('analyses_search_idx', 'book_analyses', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_table('book_images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('s3_key', sa.String(length=500), nullable=False),
    sa.Column('cloudfront_url', sa.String(length=500), nullable=True),
    sa.Column('image_type', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('book_images')
    op.drop_index('analyses_search_idx', table_name='book_analyses', postgresql_using='gin')
    op.drop_table('book_analyses')
    op.drop_index('books_status_idx', table_name='books')
    op.drop_index('books_search_idx', table_name='books', postgresql_using='gin')
    op.drop_index('books_inventory_type_idx', table_name='books')
    op.drop_index('books_category_idx', table_name='books')
    op.drop_table('books')
    op.drop_table('users')
    op.drop_table('publishers')
    op.drop_table('binders')
    op.drop_table('authors')
    # ### end Alembic commands ###
